name: Build
on:
  workflow_dispatch:
  push:
    tags:
      - "**"
jobs:
  build:
    name: Build
    runs-on: macos-13
    permissions:
      contents: write # action-gh-release
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Install Theos
      uses: Randomblock1/theos-action@da432cbe88433bafb9abf94dbbc979daab5fcf04
      with:
        # Where to install Theos
        theos-dir: ${{ github.workspace }}/theos
        # Where to clone Theos from (git URL)
        theos-src: https://github.com/theos/theos
        # Where to clone the iOS SDKs from (GitHub repository URL)
        theos-sdks: https://github.com/theos/sdks
        # Which branch to clone from SDK repo
        theos-sdks-branch: master
        # Whether to enable Orion, which adds support for Swift tweaks
        orion: false
    - name: Move FLEX to src folder
      run: mkdir src; find FLEX/Classes -type f \( -name "*.h" -o -name "*.m" -o -name "*.mm" -o -name "*.c" \) -exec cp {} src/ \;
    - name: Build package
      run: make package
    - name: 'Upload binary as artifact'
      uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
      with:
        files: 'packages/**'
